### ISSUE TITLE
Undefined index "image" when using with API

### ISSUE THREAD

**Issue by jonasfeige** [sylvainjule/kirby-imageboxes#8]
Hi Sylvain.

Running into some issues when trying to use the plugin with an `api` fetch.

First, there seem to be some namespace declarations missing [here](https://github.com/sylvainjule/kirby-imageboxes/blob/bd521302f4c2d9b928429218a34fcf853ca8fafd/lib/options/imageboxes-options.php#L3), namely:

```
use Kirby\Cms\App;
use Kirby\Form\OptionsApi;
```

After fixing this, I get the following error:

`Undefined index: image in file: .../site/plugins/imageboxes/lib/options/imageboxes-options.php line: 79`

My blueprint looks like this:

```
termine:
    type: imageboxes
    options: api
    api:
      url: "{{ kirby.option('coaUrl') }}/termine.json"
      text: "{{ item.date }} — {{ item.title }}"
      value: "{{ item.title.slug }}"
      image: "{{ item.image }}"
```

The returned json looks good, returning a regular absolute URL for the image.

Any idea?
